/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RoomState =
  | DecisionRoom
  | ExampleRoom1
  | ExampleRoom2
  | ExampleRoom3
  | RoomceptionRoom;
export type DecisionRoom =
  | {
      type: 'decisionRoom';
      playerState: 'AtEntrance';
      isSheeple: boolean;
    }
  | {
      type: 'decisionRoom';
      playerState: 'AttemptingToLeave';
      isSheeple: false;
    };

export interface GameState {
  roomState: RoomState;
}
export interface ExampleRoom1 {
  type: 'exampleRoom1';
  playerState: 'AtEntrance';
}
export interface ExampleRoom2 {
  type: 'exampleRoom2';
  playerState: 'AtEntrance' | 'State2A' | 'State2B';
}
export interface ExampleRoom3 {
  type: 'exampleRoom3';
  playerState: 'AtEntrance' | 'State3A' | 'State3B';
  laps: number;
}
export interface RoomceptionRoom {
  type: 'roomceptionRoom';
  playerState: 'AtEntrance';
}
