name: Klicker Knight CI

on:
  pull_request:
    branches:
      - main

jobs:
  klicker-knight-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install
        run: npm ci
      - name: Lint Code
        if: always()
        run: npm run lint:ts
      - name: Lint Docs
        if: always()
        run: npm run lint:md
      - name: Lint Yaml
        if: always()
        run: npm run lint:yaml
      - name: Test
        if: always()
        run: npm test
      - name: Run App
        if: always()
        run: npm run dev
