name: Klicker Knight CI

on:
  pull_request:
    branches:
      - main

jobs:
  klicker-knight-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: npm ci
      - name: CI
        run: npm run klicker-knight
